---
- name: make sure oledb msi is installed on hosts
  hosts: win
  tasks:
  - name: install Msi  oledb if not present
    ansible.windows.win_package:
      path: \\path\msoledbsql19-64.msi # path to msi
      state: present
      arguments:
      - /passive                          # run quietly
      - /qn                               # run quietly
      - IACCEPTMSOLEDBSQLLICENSETERMS=YES # accept EULA
      user_name:                          # might not need if using kerberos
      user_password: 

