---
- name: Create IIS Website
  hosts: iis
  vars:
    iis_sites: # can add more sites here to deploy
      - name: web.test.co.il                                 # name of site
        port: 80                                               # default binding port
        path: "\\\\path\\x\\InetPub\\path" # physical path
        connect_as: specific_user                              # connect as specific user (user will be defined in powershell script)


  tasks:
   - name: Create a new application pool in 'Started' state # creates the application pool for each new website defined in iis_sites with the same name 
     win_iis_webapppool:
       name: "{{ item.name }}"
       state: started
     with_items: "{{ iis_sites }}"

   - name: Create IIS site  # creates the site ans conects it to the new application pool
     win_iis_website:
       name: "{{ item.name }}"
       state: started                    
       hostname: "{{ item.name }}"
       application_pool: "{{ item.name }}"
       port: "{{ item.port }}"
       physical_path: "{{ item.path }}"
     with_items: "{{ iis_sites }}"

   - name: set the connecting user to comax@comaxdev # run a powershell script that will configure the connecting user
     win_shell: |
       powershell.exe -ExecutionPolicy Bypass -File \\path\Ansible\ConfWebDev.ps1 "{{item.name}}"
     with_items: "{{ iis_sites }}"

   - name: display post install message # post install message
     debug:
       msg: "Site Deployed: {{ item.name }}"
     with_items: "{{ iis_sites }}"


#   - name: set webapplication on new site
#     community.windows.win_iis_webapplication:
#       name: web.test.co.il
#       site: web.test.co.il
#       state: present
#       connect_as: specific_user
#       username:
#       password: 
#       physical_path: "{{ item.path }}"
#     with_items: "{{ iis_sites }}"

